### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by iambadash01** [gaby/ABS#17] opened 2023-01-11 12:03 UTC
extension is not working properly in browser please update it.

**Comment by rahul20110** [comment] 2023-01-12 13:53
Yeah it is creating many problems

**Comment by iambadash01** [comment] 2023-01-12 16:22
> Yeah it is creating many problems

Did you find any solutions

**Comment by rahul20110** [comment] 2023-01-12 16:24
Not till now, but I am trying to find it. Even I tried to export it in manifest v3 but doing that, it lost the main feature i.e. automatic. so I gave up on this :(

**Comment by iambadash01** [comment] 2023-01-12 17:20
> Not till now, but I am trying to find it. Even I tried to export it in manifest v3 but doing that, it lost the main feature i.e. automatic. so I gave up on this :(

How many accounts do you have, did you ever get banned if yes why?

**Comment by Akhilesh9878** [comment] 2023-01-14 18:14
hii i am also facing many problem now. extension is not working fine after manifest 3 come

**Comment by gaby** [comment] 2023-02-06 00:05
Duplicate of #10

**Closed as completed by gaby** 2023-02-06 00:05 UTC

**Comment by rahul20110** [comment] 2023-02-10 14:13
@iambadash01 I Found the mistake. Now working properly
